name: Translate issues

permissions:
  contents: write

on:
  push:
    paths:
      - 'issues.ko.json'
      - 'tools/translate.py'
      - '.github/workflows/translate.yml'
  workflow_dispatch: {}

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run translator
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: python tools/translate.py

      # ← 셸 스크립트 대신 검증된 자동 커밋 액션 사용
      - name: Commit translated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-translate issues"
          file_pattern: |
            issues.en.json
            issues.ja.json
          branch: ${{ github.ref_name }}
